### ISSUE TITLE
if文のリファクタリング

### ISSUE THREAD

**Issue by tkoyama1988** [shimo-yuki/task-app#3]
https://github.com/shimo-yuki/task-app/blob/master/app/controllers/tasks_controller.rb#L59-L61
```
if @task.user != current_user
  redirect_to root_path
end

↓

redirect_to root_path if @task.user != current_user
```
1行で書けるので試してみてくださいー

**Comment by YujiMiyashita** [comment]
edit_taskメソッド名を変更した方が良い？

**Comment by shimo-yuki** [comment]
edit_taskからset_mytaskへ変更
